"""Agregar campo hash_contenido a CatalogoBaseAcumulado

Revision ID: 03c10a709826
Revises: 6a5919b5b299
Create Date: 2025-06-09 11:29:13.825980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c10a709826'
down_revision = '6a5919b5b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_contenido', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.drop_column('hash_contenido')

    # ### end Alembic commands ###
