"""Agregar campo estatus a ConceptoCatalogo

Revision ID: 230ff6487891
Revises: b0b331c32bfb
Create Date: 2025-06-09 13:02:47.046007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230ff6487891'
down_revision = 'b0b331c32bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto_catalogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto_catalogo', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
