"""Agregar campos de anticipo fijo al modelo Contrato

Revision ID: 3ed01b91a64f
Revises: 838ee66de265
Create Date: 2025-06-18 18:03:49.055847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed01b91a64f'
down_revision = '838ee66de265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anticipo_sin_iva', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iva_anticipo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_anticipo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('total_anticipo')
        batch_op.drop_column('iva_anticipo')
        batch_op.drop_column('anticipo_sin_iva')

    # ### end Alembic commands ###
