"""Initial migration

Revision ID: 651afd408196
Revises: 
Create Date: 2025-05-21 18:52:38.619468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651afd408196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centro', sa.String(length=100), nullable=False),
    sa.Column('codigo_centro', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contrato', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('monto_sin_iva', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('porcentaje_anticipo', sa.Float(), nullable=True),
    sa.Column('anticipo_total', sa.Float(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('ubicacion_trabajos', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centro.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobacion_concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('clave_concepto', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_subida', sa.Date(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_inicio_trab_est', sa.Date(), nullable=True),
    sa.Column('fecha_fin_trab_est', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('total_con_iva', sa.Float(), nullable=True),
    sa.Column('amortizacion', sa.Float(), nullable=True),
    sa.Column('nombre_contrato', sa.String(length=255), nullable=True),
    sa.Column('clave_contrato', sa.String(length=100), nullable=True),
    sa.Column('numero_estimacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('monto_sin_iva', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avance_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('version_catalogo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['version_catalogo_id'], ['catalogo_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepto_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('partida', sa.String(length=100), nullable=True),
    sa.Column('nombre_partida', sa.String(length=100), nullable=True),
    sa.Column('concepto', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['catalogo_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_estimacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimacion_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('clave_concepto', sa.String(length=20), nullable=False),
    sa.Column('nombre_partida', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad_estimacion', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estimacion_id'], ['estimacion.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importe_partida_estimacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimacion_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('numero_partida', sa.String(length=20), nullable=False),
    sa.Column('nombre_partida', sa.String(length=255), nullable=False),
    sa.Column('importe_original', sa.Float(), nullable=False),
    sa.Column('importe_estimacion', sa.Float(), nullable=False),
    sa.Column('importe_anterior', sa.Float(), nullable=False),
    sa.Column('importe_acumulado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estimacion_id'], ['estimacion.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('parcialidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefiniquito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('version_original_id', sa.Integer(), nullable=False),
    sa.Column('version_actualizada_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), nullable=False),
    sa.Column('total_original', sa.Float(), nullable=True),
    sa.Column('total_actualizado', sa.Float(), nullable=True),
    sa.Column('diferencia_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['version_actualizada_id'], ['catalogo_version.id'], ),
    sa.ForeignKeyConstraint(['version_original_id'], ['catalogo_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aprobacion_id', sa.Integer(), nullable=False),
    sa.Column('numero_revision', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['aprobacion_id'], ['aprobacion_concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_avance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avance_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_avance', sa.Float(), nullable=False),
    sa.Column('subtotal_avance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['avance_id'], ['avance_obra.id'], ),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_prefiniquito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefiniquito_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('partida', sa.String(length=20), nullable=True),
    sa.Column('nombre_partida', sa.String(length=100), nullable=True),
    sa.Column('clave_concepto', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario_original', sa.Float(), nullable=True),
    sa.Column('cantidad_original', sa.Float(), nullable=True),
    sa.Column('subtotal_original', sa.Float(), nullable=True),
    sa.Column('precio_unitario_actualizado', sa.Float(), nullable=True),
    sa.Column('cantidad_actualizada', sa.Float(), nullable=True),
    sa.Column('subtotal_actualizado', sa.Float(), nullable=True),
    sa.Column('diferencia_cantidad', sa.Float(), nullable=True),
    sa.Column('diferencia_subtotal', sa.Float(), nullable=True),
    sa.Column('tipo_cambio', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto_catalogo.id'], ),
    sa.ForeignKeyConstraint(['prefiniquito_id'], ['prefiniquito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_prefiniquito')
    op.drop_table('detalle_avance')
    op.drop_table('revision_concepto')
    op.drop_table('prefiniquito')
    op.drop_table('pago')
    op.drop_table('importe_partida_estimacion')
    op.drop_table('detalle_estimacion')
    op.drop_table('concepto_catalogo')
    op.drop_table('concepto')
    op.drop_table('avance_obra')
    op.drop_table('partida')
    op.drop_table('factura')
    op.drop_table('estimacion')
    op.drop_table('catalogo_version')
    op.drop_table('aprobacion_concepto')
    op.drop_table('contrato')
    op.drop_table('tarea')
    op.drop_table('empresa')
    op.drop_table('cliente')
    op.drop_table('centro')
    # ### end Alembic commands ###
