"""Agregar modelo CatalogoBaseAcumulado

Revision ID: 6a5919b5b299
Revises: 2f0de2e49641
Create Date: 2025-06-09 11:13:21.194997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5919b5b299'
down_revision = '2f0de2e49641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_base_acumulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_version', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('fecha_subida',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_version', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fecha_subida',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    op.drop_table('catalogo_base_acumulado')
    # ### end Alembic commands ###
