"""Agregar tabla DeduccionContrato

Revision ID: 804f40023136
Revises: a12f7ac3c424
Create Date: 2025-06-13 12:32:38.426889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804f40023136'
down_revision = 'a12f7ac3c424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deduccion_contrato')
    # ### end Alembic commands ###
