"""Agregar tabla DeduccionEstimacion

Revision ID: 838ee66de265
Revises: 804f40023136
Create Date: 2025-06-13 12:42:02.906954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838ee66de265'
down_revision = '804f40023136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion_estimacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['estimacion_id'], ['estimacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deduccion_estimacion')
    # ### end Alembic commands ###
