"""Agregar campo contenido al modelo CatalogoBaseAcumulado

Revision ID: 92741f160250
Revises: f5f0d0cf6b41
Create Date: 2025-06-09 11:49:30.921543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92741f160250'
down_revision = 'f5f0d0cf6b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=True))
        batch_op.drop_column('conceptos_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conceptos_json', sa.TEXT(), nullable=True))
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
