"""Agrega campo descripcion a RevisionConcepto

Revision ID: a12f7ac3c424
Revises: a2400e0c2e08
Create Date: 2025-06-09 15:12:26.209005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12f7ac3c424'
down_revision = 'a2400e0c2e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
