"""Agregar campo precio_unitario a RevisionConcepto

Revision ID: a2400e0c2e08
Revises: eea0a5f81cb0
Create Date: 2025-06-09 14:43:08.890780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2400e0c2e08'
down_revision = 'eea0a5f81cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.Date(), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATE(), nullable=False))
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
