"""Agregar tabla EstatusConcepto

Revision ID: eea0a5f81cb0
Revises: 230ff6487891
Create Date: 2025-06-09 13:50:25.601544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea0a5f81cb0'
down_revision = '230ff6487891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estatus_concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('clave_concepto', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=200), nullable=True),
    sa.Column('archivo_acuse', sa.String(length=200), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aprobacion_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nombre_archivo_pdf', sa.String(length=255), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('fecha_actualizacion')

    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_pdf', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('acuse_pdf', sa.String(length=255), nullable=True))
        batch_op.drop_column('archivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('acuse_pdf')
        batch_op.drop_column('archivo_pdf')

    with op.batch_alter_table('aprobacion_concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DATE(), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('nombre_archivo_pdf')
        batch_op.drop_column('descripcion')

    op.drop_table('estatus_concepto')
    # ### end Alembic commands ###
