"""Agregar campo conceptos_json a CatalogoBaseAcumulado

Revision ID: f5f0d0cf6b41
Revises: 03c10a709826
Create Date: 2025-06-09 11:39:25.677560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f0d0cf6b41'
down_revision = '03c10a709826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conceptos_json', sa.Text(), nullable=True))
        batch_op.alter_column('hash_contenido',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_base_acumulado', schema=None) as batch_op:
        batch_op.alter_column('hash_contenido',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('conceptos_json')

    # ### end Alembic commands ###
